#!/usr/bin/env bash
# Display information about subdomains for a given domain.


if [ $# -eq 1 ]
then
    res="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
    res="$2.$1"
fi

dig $res | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print "The subdomain", b[1], "is a", $4, "record and points to", $5}'
