#!/usr/bin/env bash

# Transfers a file from our client to a server

# Check for the correct number of arguments
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i -o StrictHostKeyChecking=no "$4" "$1" "$3@$2":~
fi
