#!/usr/bin/env bash

# Transfers a file from our client to a server

# Check for the correct number of arguments
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign arguments to variables for clarity
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Perform the secure copy operation
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~
if [ "$?" -eq 0 ]; then
  echo "File transfer successful"
else
  echo "File transfer failed"
  exit 1
fi
