#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# and setting it up to serve a "Hello World" page.


# Update package list
sudo apt-get update -y

# Install nginx with `-y` to automatically answer yes to prompts
sudo pt-get install nginx -y

# ufw allow nginx and Configure nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create a basic HTML file with Hello World content
echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html

# Restart nginx to apply changes
sudo service nginx restart

# Just to make sure 
echo -e "\nConfiguration completed successfully\n"
