#!/usr/bin/env bash
#setting it up to serve a "Hello World" page.

# Update package list
apt-get update

# Install nginx with `-y` to automatically answer yes to prompts
apt-get install -y nginx

# Create a basic HTML file with Hello World content
echo "Hello World!" > /var/www/html/index.html

# Configure nginx to listen on port 80 and serve our custom HTML file
cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html
	server_name_;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	rewrite ^ https://th3-gr00t.tk/ permanent;
	error_page 404 /error_404.html;
	location = /error_404.html
}
EOF

# Restart nginx to apply changes
service nginx restart

echo -e "\nConfiguration completed successfully\n"
