#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# and setting it up to serve a "Hello World" page.


# Update package list
sudo apt-get update -y

# Install nginx with `-y` to automatically answer yes to prompts
sudo apt-get install nginx -y

# Create a basic HTML file with Hello World content
echo "Hello World!" > /var/www/html/index.html

#Creating the 404 file
sudo touch /var/www/html/error_page_404.html
echo "Ceci n'est pas une page" > /var/www/html/error_page_404.html

printf %s "server {
		listen 80 default_server;
		listen [::]:80 default_server;
		add_header X-Served-By \$hostname;

		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		
		location /redirect_me{
			return 301 http://www.youtube.com/ ;
		}

		error_page 404 /error_page_404.html;
		location = /error_page_404.html {
			root /etc/nginx/html
			internal;
		}
}" > /etc/nginx/sites-available/default

# Restart nginx to apply changes
sudo service nginx restart
