#!/usr/bin/env bash
# installing load balancer

# Updating
sudo apt-get update -y 

# Installing Haproxy
sudo apt-get install haproxy -y

# changing ownership
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend tdo_frontend
  mode http
  bind *:80
  default_backend tdo_backend

backend tdo_backend
  mode http
  balance roundrobin
  server 237907-web-01 18.233.63.62:80 check
  server 237907-web-02 54.160.77.90:80 check" >> /etc/haproxy/haproxy.cfg

# Restart haproxy to apply changes
sudo service haproxy restart
