#!/usr/bin/env bash
# Setup few rules on WEb-01 server

sudo apt-get updates -y
sudo apt install ufw -y

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
