#!/bin/bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script as root"
    exit 1
fi

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Configuration complete. localhost now resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8."

