#!/bin/bash

# Get all active IPv4 addresses using 'ip' command
ip_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Print out the IPv4 addresses
echo "Active IPv4 Addresses:"
echo "$ip_addresses"

